name: build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - run: cat config.sample.json | sed 's/"access_token",/"some_token",/' > config.json
      - run: npm ci
      - run: npm test

      - uses: codecov/codecov-action@v3

      - run: npm run build

      - if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
